### ISSUE TITLE
UAV Operator krijgt geen UAV

### ISSUE THREAD

**Issue by Pekuru** [Lowlands-Tactical/LT_Template_Base_OLD#10]
Bij selecteren van de volgende camouflage en wapenparameters, wordt tijdens het inspawnen geen UAV gegeven aan de UAV Operator.

![arma3_x64_DaFYGA8fbC](https://user-images.githubusercontent.com/9923839/120100300-61559b00-c140-11eb-8e72-7290a3e4fb1b.png)

**Afbeelding om te bewijzen dat hij geselecteerd staat als UAV Operator**

![arma3_x64_DdHtuAaYKG](https://user-images.githubusercontent.com/9923839/120100315-73cfd480-c140-11eb-8809-c47fd677b684.png)

**Resultaat**

![arma3_x64_aaFGYkqe3S](https://user-images.githubusercontent.com/9923839/120100319-7af6e280-c140-11eb-83d2-da928517d1bb.png)

**Comment by svenfire99** [comment]
De UAV operator gaat een Darter krijgen als rugzak, maar moet ff wat logica schrijven om de juiste drone te geven als je op de goeie kant / side zit. (Aka BLUFOR krijgt een BLUFOR drone en niet een CSAT drone...)
