### ISSUE TITLE
Dubbele rugzak

### ISSUE THREAD

**Issue by Pekuru** [Lowlands-Tactical/LT_Template_Base_OLD#11]
Bij inspawnen als UAV Operator met de loadout selectie `Special Forces MTP` en `NLD 2020` spawned er een dubbele rugzak die op de grond beland.

![arma3_x64_cPUIYhQubi](https://user-images.githubusercontent.com/9923839/120100436-08d2cd80-c141-11eb-87b5-362922fee3b4.jpg)

**Comment by svenfire99** [comment]
Klopt dit zou een UAV bag zijn maar deze feature was dus niet werkend. (Sinds deze rol toegevoegd was aan de template)

**Comment by svenfire99** [comment]
Duplicate of #10
