### ISSUE TITLE
Battery bug

### ISSUE THREAD

**Issue by PingWing1337** [Lowlands-Tactical/LT_Template_Base_OLD#15]
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/58b8fc303babe6f6edcba08548998b4469fb8ccb/gear/setGear.sqf#L697

Hi, JTAC geeft een error, omdat deze een string is IPV een array zoals bij alle andere addMagazines.
Verander naar: 
**_unit  addmagazines [_laserdesignatorBattery,1];**

**Comment by Pekuru** [comment]
Fixed
