### ISSUE TITLE
Acre Radio Fix

### ISSUE THREAD

**Issue by BrainlessBen** [Lowlands-Tactical/LT_Template_Base_OLD#22]
ACRE2 radio script wordt niet gestart bij start missie waardoor radios na respawn gereset worden.
Locatie:
lt_template_base\TFR\Settings.sqf

de IF statement bestaat niet waardoor acre_api-fnc-setupMission nooit afgetrapt wordt.

Oplossing:
Gehele if statement vervangen met het volgende.
`[true,true] remoteExec ["acre_api_fnc_setupMission",allPlayers];`
`ACRE_TEST_OCCLUSION = false;`

**Comment by maarten2702** [comment]
Fix in add sets up player radio on mission load / respawn
