### ISSUE TITLE
Player colour team onthouden.

### ISSUE THREAD

**Issue by BrainlessBen** [Lowlands-Tactical/LT_Template_Base_OLD#23]
Na respawn wordt de kleur van de speler niet onthouden en gereset naar wat voor kleur je had in het begin.
Dit is makkelijk op te lossen door in de common.sqf een regels toe te voegen.

`player assignTeam (player getVariable ["lt_unit_color","MAIN"]);`

de common.sqf wordt bij onPlayerRespawn.sqf ook afgetrapt. waardoor de kleur van de unit hersteld wordt naar wat voor kleur die had voor de respawn.

**Comment by maarten2702** [comment]
See Commit add it fix from issues #23
