### ISSUE TITLE
Defense Module Mortars

### ISSUE THREAD

**Issue by Pekuru** [Lowlands-Tactical/LT_Template_Base_OLD#5]
Mortars werken niet. Geen enkele value werkt.

**Comment by svenfire99** [comment]
Graag meer uitleg

**Comment by Pekuru** [comment]
![arma3_x64_8bAY49IQMn](https://user-images.githubusercontent.com/9923839/120100925-a4653d80-c143-11eb-9659-f6048898f648.png)

**Comment by svenfire99** [comment]
Schreeuwen helpt niet

**Comment by Pekuru** [comment]
> mfw told to report bugs on issue tracker
> tells issue
> 'meer uitleg'

'Het werkt niet' lijkt me simpele taal. Waarom het niet werkt? Geen idee, ik werk niet aan het template. Ongeacht values vallen er geen mortieren/houwitsers ect.

**Comment by svenfire99** [comment]
Dude je kan ook gwn normaal praten.
En Defence module krijgt een full overhaul, wanneer ga ik hieraan beginnen? Ergens begin zomervakantie.
Voor nu wordt mortar uitgezet van defence module, want het werkt nie. En ga er nu geen tijd aan verspillen.
