### ISSUE TITLE
Special Forces MTP heeft zwart uniform

### ISSUE THREAD

**Issue by Pekuru** [Lowlands-Tactical/LT_Template_Base_OLD#8]
Zie titel en screenshots.

![20210525182325_1](https://user-images.githubusercontent.com/9923839/119533956-acf5f680-bd86-11eb-8197-5f01d56d5606.jpg)

![20210525182259_1](https://user-images.githubusercontent.com/9923839/119533982-b54e3180-bd86-11eb-88c1-bfc7dd049cf8.jpg)

**Comment by ShiftySean** [comment]
MTP was sowieso al een verkeerde benaming, de Multi Terrain Pattern camo is een variant van multicam van het britse leger. Nederland gebruikt gewoon Multicam van Crye Precision voor de SF en meer recentelijk ook gewoon voor uitgezonden eenheden totdat NFP in volle gang komt, just as an fyi ;)

**Comment by Pekuru** [comment]
> MTP was sowieso al een verkeerde benaming, de Multi Terrain Pattern camo is een variant van multicam van het britse leger. Nederland gebruikt gewoon Multicam van Crye Precision voor de SF en meer recentelijk ook gewoon voor uitgezonden eenheden totdat NFP in volle gang komt, just as an fyi ;)

JE SNAPT WAT IK BEDOEL SHIFTY >:(

**Comment by svenfire99** [comment]
Gefixed met de volgende template build!
